import unittest 
from code.Valorant_Tracker.matchhistory import compMatchHistory

class TestMatchHistory(unittest.TestCase):
    def test_getAccData(self):
        mh = compMatchHistory(None, None)
        self.assertEqual(mh.getAccData(), False)
        mh = compMatchHistory('HamieMcBamie', '4186')
        self.assertEqual(mh.getAccData(), True)
        mh = compMatchHistory('InitiatorToRad','5112')
        self.assertEqual(mh.getAccData(), True)
        mh = compMatchHistory('PeeeePoooo81818828381881838281819382918','8888')
        self.assertEqual(mh.getAccData(), False)
        mh = compMatchHistory('PROD','4545')
        self.assertEqual(mh.getAccData(), True)
        mh = compMatchHistory('Lifended','4188')
        self.assertEqual(mh.getAccData(), False)
        
    def test_formatAccData(self):
        mh = compMatchHistory(None, None)
        mh.getAccData()
        self.assertEqual(mh.formatAccData(), False)
        mh = compMatchHistory('HamieMcBamie', '4186')
        mh.getAccData()
        self.assertEqual(mh.formatAccData(), True)
        mh = compMatchHistory('InitiatorToRad','5112')
        mh.getAccData()
        self.assertEqual(mh.formatAccData(), True)
        mh = compMatchHistory('PeeeePoooo81818828381881838281819382918','8888')
        mh.getAccData()
        self.assertEqual(mh.formatAccData(), False)
        mh = compMatchHistory('PROD','4545')
        mh.getAccData()
        self.assertEqual(mh.formatAccData(), True)
        mh = compMatchHistory('Lifended','4188')
        mh.getAccData()
        self.assertEqual(mh.formatAccData(), False)
    
    def test_getMmrHistory(self):
        mh = compMatchHistory(None, None)
        mh.getAccData()
        mh.formatAccData()
        self.assertEqual(mh.getMmrHistory(), False)
        mh = compMatchHistory('HamieMcBamie', '4186')
        mh.getAccData()
        mh.formatAccData()
        self.assertEqual(mh.getMmrHistory(), True)
        mh = compMatchHistory('InitiatorToRad','5112')
        mh.getAccData()
        mh.formatAccData()
        self.assertEqual(mh.getMmrHistory(), True)
        mh = compMatchHistory('PeeeePoooo81818828381881838281819382918','8888')
        mh.getAccData()
        mh.formatAccData()
        self.assertEqual(mh.getMmrHistory(), False)
        mh = compMatchHistory('PROD','4545')
        mh.getAccData()
        mh.formatAccData()
        self.assertEqual(mh.getMmrHistory(), True)
        mh = compMatchHistory('Lifended','4188')
        mh.getAccData()
        mh.formatAccData()
        self.assertEqual(mh.getMmrHistory(), False)
        
    def test_formatMmrData(self):
        mh = compMatchHistory(None, None)
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        self.assertEqual(mh.formatMmrData(), False)
        mh = compMatchHistory('HamieMcBamie', '4186')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        self.assertEqual(mh.formatMmrData(), True)
        mh = compMatchHistory('InitiatorToRad','5112')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        self.assertEqual(mh.formatMmrData(), True)
        mh = compMatchHistory('PeeeePoooo81818828381881838281819382918','8888')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        self.assertEqual(mh.formatMmrData(), False)
        mh = compMatchHistory('PROD','4545')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        self.assertEqual(mh.formatMmrData(), True)
        mh = compMatchHistory('Lifended','4188')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        self.assertEqual(mh.formatMmrData(), False)
        
    def test_getPrevMmr(self):
        mh = compMatchHistory(None, None)
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        mh.formatMmrData()
        self.assertEqual(mh.getPrevMmr(), False)
        mh = compMatchHistory('HamieMcBamie', '4186')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        mh.formatMmrData()
        self.assertEqual(mh.getPrevMmr(), True)
        mh = compMatchHistory('InitiatorToRad','5112')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        mh.formatMmrData()
        self.assertEqual(mh.getPrevMmr(), True)
        mh = compMatchHistory('PeeeePoooo81818828381881838281819382918','8888')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        mh.formatMmrData()
        self.assertEqual(mh.getPrevMmr(), False)
        mh = compMatchHistory('PROD','4545')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        mh.formatMmrData()
        self.assertEqual(mh.getPrevMmr(), True)
        mh = compMatchHistory('Lifended','4188')
        mh.getAccData()
        mh.formatAccData()
        mh.getMmrHistory()
        mh.formatMmrData()
        self.assertEqual(mh.getPrevMmr(), False)
        
    
            